# -*- coding: utf-8 -*-
"""csat_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3Qabkc2tOq0bkCv6VuQnvhc8woSyAC3

# Mounting From Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Importing Rice Courses"""

import pandas as pd
path = "/content/drive/MyDrive/rice_course_pages.json"
df = pd.read_json(path)

print(df.head())

df[(df['subject'] == "MATH") & (df["course_number"] == 101)]

df["course_number"] = (

    df["raw_text"]

    .str.split("\n")

    .str[0]

    .str.split()

    .str[1]
    .astype(int)

)

"""# Dropping Duplicates and Refining Prerequisite"""

## Dropping Duplicates

df["term"] = (

    df.groupby(["subject", "course_number"])["term"]

    .transform(

        lambda x: (

            "Both"

            if x.astype(str).str.contains("Fall", case=False, na=False).any()

            and x.astype(str).str.contains("Spring", case=False, na=False).any()

            else x.dropna().iloc[0] if len(x.dropna()) > 0 else None

        )

    )

)


df = df.drop_duplicates(
    subset=["subject", "course_number"]
).copy()

df.head()

df[(df["subject"] == "COMP") & (df["course_number"] == 222)]

## Parsing Prerequisite

import re
import json
def tokenize(expr):
    return re.findall(r"[A-Z]{4}\s+\d{3}|AND|OR|\(|\)", expr)

def parse_prereq(expr):
    tokens = tokenize(expr)
    pos = 0

    def parse_expression():
        return parse_or()

    def parse_or():
        nonlocal pos
        left = parse_and()

        conditions = [left]

        while pos < len(tokens) and tokens[pos] == "OR":
            pos += 1
            conditions.append(parse_and())

        if len(conditions) == 1:
            return left

        return {
            "type": "OR",
            "conditions": conditions
        }

    def parse_and():
        nonlocal pos
        left = parse_factor()

        conditions = [left]

        while pos < len(tokens) and tokens[pos] == "AND":
            pos += 1
            conditions.append(parse_factor())

        if len(conditions) == 1:
            return left

        return {
            "type": "AND",
            "conditions": conditions
        }

    def parse_factor():
        nonlocal pos

        token = tokens[pos]

        if token == "(":
            pos += 1
            node = parse_expression()

            if pos < len(tokens) and tokens[pos] == ")":
                pos += 1

            return node

        pos += 1
        return {
            "course": token
        }

    return parse_expression()
prereq = parse_prereq("(MATH 212 OR MATH 232) AND (MATH 355 OR MATH 354)")
print(json.dumps(prereq, indent=2))



import pandas as pd

def safe_parse_prereq(x):

    if pd.isna(x) or str(x).strip() == "":

        return None

    try:

        return parse_prereq(str(x))

    except Exception as e:

        return {

            "error": str(e),

            "raw": str(x)

        }

df = df.copy()

df["prereq_tree"] = df["prerequisites"].apply(safe_parse_prereq)

print(

    json.dumps(

        df[

            (df['subject'] == "COMP") &

            (df['course_number'] == 414)

        ]['prereq_tree'].iloc[0],

        indent=2

    )

)

"""# Applying C-SAT Model"""

## Installing ortools
!pip install ortools

degree_requirements = [
    {
        "id": "required_core",
        "requirement_type": "required_courses",
        "courses": [
            "COMP 140",
            "COMP 182",
            "COMP 215",
            "COMP 222",
            "COMP 301",
            "COMP 312",
            "COMP 318",
            "COMP 321",
            "COMP 382"
        ],
        "min_count": 9,
        "max_count": 9
    },

    {
        "id": "calculus_1",
        "requirement_type": "choose_n",
        "courses": [
            "MATH 101",
            "MATH 105"
        ],
        "min_count": 1,
        "max_count": 1
    },

    {
        "id": "calculus_2",
        "requirement_type": "choose_n",
        "courses": [
            "MATH 102",
            "MATH 106"
        ],
        "min_count": 1,
        "max_count": 1
    },

    {
        "id": "multivariable_calculus",
        "requirement_type": "choose_n",
        "courses": [
            "MATH 212",
            "MATH 222",
            "MATH 232"
        ],
        "min_count": 1,
        "max_count": 1
    },

    {
        "id": "probability_statistics",
        "requirement_type": "choose_n",
        "courses": [
            "ELEC 303",
            "STAT 310",
            "STAT 311",
            "STAT 312",
            "STAT 315",
            "DSCI 301"
        ],
        "min_count": 1,
        "max_count": 1
    },

    {
        "id": "linear_algebra",
        "requirement_type": "choose_n",
        "courses": [
            "CMOR 302",
            "CMOR 303",
            "MATH 221",
            "MATH 354",
            "MATH 355"
        ],
        "min_count": 1,
        "max_count": 1
    },

    {
        "id": "design_requirement",
        "requirement_type": "choose_n",
        "courses": [
            "COMP 402",
            "COMP 410",
            "COMP 413",
            "COMP 416",
            "COMP 460",
            "COMP 461"
        ],
        "min_count": 1,
        "max_count": 1
    },

    {
        "id": "systems",
        "requirement_type": "choose_n",
        "courses": [
            "COMP 412",
            "COMP 421",
            "COMP 422",
            "COMP 427",
            "COMP 429",
            "COMP 432",
            "COMP 436",
            "COMP 458"
        ],
        "min_count": 1,
        "max_count": 1
    },

    {
        "id": "application_domains",
        "requirement_type": "choose_n",
        "courses": [
            "COMP 418",
            "COMP 431",
            "COMP 440",
            "COMP 442",
            "COMP 447",
            "COMP 450",
            "COMP 459",
            "COMP 462",
            "COMP 471",
            "COMP 484"
        ],
        "min_count": 1,
        "max_count": 1
    },

    {
        "id": "theory",
        "requirement_type": "choose_n",
        "courses": [
            "COMP 409",
            "COMP 411",
            "COMP 414",
            "COMP 423",
            "COMP 448",
            "COMP 463",
            "COMP 475",
            "COMP 480",
            "COMP 481"
        ],
        "min_count": 1,
        "max_count": 1
    },

    {

        "id": "comp_electives",

        "requirement_type": "choose_n",

        "filters": {

            "subject": "COMP",

            "min_level": 300

        },

        "min_count": 2,

        "constraints": {

            "max_from_group": [

                {

                    "courses": ["COMP 390", "COMP 490", "COMP 491"],

                    "max_count": 1

                }

            ],

            "allowed_600_level_courses": ["COMP 631", "COMP 646"],

            "allow_500_level": True

        }

    }
]

df[(df["subject"] == "COMP") & (df["course_number"] == 182)]['prereq_tree']

"""# Creating Cross-Listed Course Column"""

import re

def parse_cross_list(raw_text):

    if pd.isna(raw_text):

        return []

    match = re.search(

        r"Cross-list:\s*([A-Z]{2,5}\s+\d{3})",

        raw_text

    )

    if match:

        return [match.group(1).strip()]

    return []

df["cross_list"] = df["raw_text"].apply(parse_cross_list)

df[(df['subject'] == "COMP") & (df['course_number'] == 484)]

"""#Prereq Requirement"""

from ortools.sat.python import cp_model

semesters = range(8)


def get_prereq_tree(course):
    subject, course_number = course.split(" ")

    row = df[
        (df["subject"] == subject) &
        (df["course_number"] == int(course_number))
    ]

    if row.empty:
        return None

    tree = row["prereq_tree"].iloc[0]

    if not isinstance(tree, dict):
        return None

    return tree


def collect_prereq_courses(tree):
    if tree is None:
        return set()

    if "course" in tree:
        return {tree["course"]}

    courses = set()

    for condition in tree["conditions"]:
        courses |= collect_prereq_courses(condition)

    return courses


def prereq_satisfied_bool(tree, s, model, take, completed_courses):
    satisfied = model.new_bool_var(f"prereq_satisfied_sem_{s}_{id(tree)}")

    if not isinstance(tree, dict):
        model.add(satisfied == 0)
        return satisfied

    if "course" in tree:
        prereq_course = tree["course"]

        # Already completed before planning starts
        if prereq_course in completed_courses:
            model.add(satisfied == 1)
            return satisfied

        # Prereq not in planning model
        if (prereq_course, 0) not in take:
            model.add(satisfied == 0)
            return satisfied

        taken_before = sum(
            take[(prereq_course, prev_s)]
            for prev_s in semesters
            if prev_s < s
        )

        model.add(taken_before >= 1).only_enforce_if(satisfied)
        model.add(taken_before == 0).only_enforce_if(satisfied.Not())

        return satisfied

    child_bools = [
        prereq_satisfied_bool(condition, s, model, take, completed_courses)
        for condition in tree["conditions"]
    ]

    if tree["type"] == "AND":
        model.add(sum(child_bools) == len(child_bools)).only_enforce_if(satisfied)
        model.add(sum(child_bools) <= len(child_bools) - 1).only_enforce_if(satisfied.Not())

    elif tree["type"] == "OR":
        model.add(sum(child_bools) >= 1).only_enforce_if(satisfied)
        model.add(sum(child_bools) == 0).only_enforce_if(satisfied.Not())

    else:
        model.add(satisfied == 0)

    return satisfied

"""# Test"""

print(get_prereq_tree("COMP 414"))

"""#Distribution Requirement"""

import re

#Parse Distribution from Raw Text

def parse_distribution(raw_text):

    match = re.search(

        r"Distribution Group:\s*\n(.+)",

        raw_text

    )

    if match:

        return match.group(1).strip()

    return None

# Add Distribution Columns

df["distribution"] = df["raw_text"].apply(parse_distribution)


# Distribution satisfaction function

def satisfy_distribution(model):
    satisfied = model.new_bool_var(f"dist_satisfied_grou_{s}")

print(df.columns)

"""# Add Credit Hours"""

import re

# Parse Credit Hours from Raw Text
def parse_credit_hour(raw_text):

    match = re.search(
        r"Credit Hours:\s*\n(.+)",
        raw_text
    )

    if match:
        return match.group(1).strip()

    return None


# Add credit_hours column
df["credit_hours"] = df["raw_text"].apply(parse_credit_hour)


# Keep only integer credit hours
df = df[
    df["credit_hours"]
    .astype(str)
    .str.fullmatch(r"\d+")
].copy()


# Convert to int
df["credit_hours"] = df["credit_hours"].astype(int)

df.head()

"""#Add Analyzing Diversity Requirements"""

#Parse Analyzing from Raw Text

def parse_diversity(raw_text):

    match = re.search(

        r"Analyzing Diversity:\s*\n(.+)",

        raw_text

    )

    if match:

        return match.group(1).strip()

    return None

# Add Diversity Columns

df["analyzing_diversity"] = df["raw_text"].apply(parse_diversity)

df[(df['subject'] == "COMP") & (df["course_number"] == 140)]["distribution"].iloc[0] == "Distribution Group III"

print(df[(df["subject"] == "COMP") & (df["course_number"] == 440)]["prereq_tree"].iloc[0])

"""# Apply the CP-SAT Model to complete CS Degree Requirement"""

import pandas as pd
from ortools.sat.python import cp_model

# -----------------------------
# Upcoming Term
# -----------------------------

current_term = "Spring"

year = "Freshman"

# -----------------------------

# Remaining Semesters

# -----------------------------

year_order = [

    "Freshman",

    "Sophomore",

    "Junior",

    "Senior"

]

term_order = [

    "Fall",

    "Spring"

]

# -----------------------------
# Course that have been taken
# -----------------------------


completed_courses = {

    "MATH 101": 3,

    "MATH 102": 3,

    "ECON 113": 3,

    "ECON 111": 3,

    "PHYS 101": 3,

    "PHYS 102": 3,

    "COMP 105": 3,

    # freshman fall completed

    "COMP 140": 4,

    "MATH 212": 3,

    "MATH 355": 3,

    "ECON 100": 3

}

# -----------------------------
# Courses student wants to take
# -----------------------------


preferred_courses = {

    "COMP 341": 3,

    "COMP 449": 4,

    "COMP 484": 3


}

# -----------------------------
# Courses student wants to avoid
# -----------------------------


avoid_courses = {

    "COMP 414": 3



}

# -----------------------------
# Different optimization
# -----------------------------

optimization = "balanced" # (graduate early, balanced)



# Total semesters in degree

total_semesters = 8

# Current semester index

current_year_index = year_order.index(year)

current_term_index = term_order.index(current_term)

current_semester_number = (

    current_year_index *

    2 + current_term_index

)

# Remaining semesters including current

remaining_semesters = (

    total_semesters

    - current_semester_number

)

semesters = range(remaining_semesters)


# Printing semesters

print("Current term:", current_term)
print("Current year:", year)
print("Current semester number:", current_semester_number)
print("Remaining semesters:", list(semesters))





def normalize_course(row):
    subject = str(row["subject"]).strip()

    if pd.isna(row["course_number"]):
        return None

    try:
        course_number = str(int(row["course_number"]))
    except:
        return None

    if subject == "" or subject == "nan":
        return None

    return f"{subject} {course_number}"


def main(

    df,

    degree_requirements,

    completed_courses,

    preferred_courses,

    avoid_courses,

    current_term,

    year,

    optimization="balanced"
) -> None:
    model = cp_model.CpModel()

    distribution_requirements = {
        "Distribution Group I": 3,
        "Distribution Group II": 3,
        "Distribution Group III": 3,
    }

    # -----------------------------
    # Precompute course metadata
    # -----------------------------

    course_to_row = {}
    course_to_credits = {}
    distribution_courses = {
        "Distribution Group I": [],
        "Distribution Group II": [],
        "Distribution Group III": [],
    }
    diversity_courses = []
    fwis_courses = []
    lpap_courses = []

    for _, row in df.iterrows():
        course = normalize_course(row)

        if course is None:
            continue

        if course not in course_to_row:
            course_to_row[course] = row

        try:
            credits = int(row["credit_hours"])
            course_to_credits[course] = credits
        except:
            pass

        dist = row.get("distribution")

        if dist in distribution_courses:
            distribution_courses[dist].append(course)

        if row.get("analyzing_diversity") == "Yes":
            diversity_courses.append(course)

        if course.startswith("FWIS"):
            fwis_courses.append(course)
        if course.startswith("LPAP"):
            lpap_courses.append(course)

    #Print metadata summary

    print("----Metadata Summary----")
    print("Total courses in df:", len(course_to_row))
    print("Courses with credits:", len(course_to_credits))
    print("Distribution Group I courses:", len(distribution_courses["Distribution Group I"]))
    print("Distribution Group II courses:", len(distribution_courses["Distribution Group II"]))
    print("Distribution Group III courses:", len(distribution_courses["Distribution Group III"]))
    print("Diversity courses:", len(diversity_courses))
    print("FWIS courses:", len(fwis_courses))

    # -----------------------------
    # Collect relevant courses only
    # -----------------------------

    all_courses = set()

    for req in degree_requirements:
        if "courses" in req:
            all_courses.update(req["courses"])

    for courses in distribution_courses.values():
        all_courses.update(courses)

    all_courses.update(diversity_courses)
    all_courses.update(fwis_courses)
    all_courses.update(lpap_courses)
    all_courses.update(preferred_courses)
    all_courses.update(avoid_courses)

    # Keep only courses that exist in df
    all_courses = {
        course for course in all_courses
        if course in course_to_row
    }

    # Add filter-based requirement courses, such as COMP electives

    for req in degree_requirements:

        if "filters" not in req:

            continue

        filters = req.get("filters", {})

        constraints = req.get("constraints", {})

        for course, row in course_to_row.items():

            subject = str(row["subject"]).strip()

            try:

                course_number = int(row["course_number"])

            except:

                continue

            if "subject" in filters and subject != filters["subject"]:

                continue

            if "min_level" in filters and course_number < filters["min_level"]:

                continue

            if 500 <= course_number < 600:

                if constraints.get("allow_500_level", True) is False:

                    continue

            if course_number >= 600:

                allowed_600 = set(

                    constraints.get("allowed_600_level_courses", [])

                )

                if course not in allowed_600:

                    continue

            all_courses.add(course)

    # ---- Additional Debugging for Course Eligibility ----
    print("\n---- Course Eligibility Summary (after filtering) ----")
    print(f"Total unique courses considered by the model: {len(all_courses)}")

    for req in degree_requirements:
        req_id = req.get("id", "Unnamed Requirement")
        eligible_for_req = set()
        if "courses" in req:
            eligible_for_req.update(c for c in req["courses"] if c in all_courses)
        elif "filters" in req:
            filters = req.get("filters", {})
            constraints = req.get("constraints", {})
            for course in all_courses:
                row = course_to_row[course]
                subject = str(row["subject"]).strip()
                try:
                    course_number = int(row["course_number"])
                except:
                    continue

                is_eligible = True
                if "subject" in filters and subject != filters["subject"]:
                    is_eligible = False
                if "min_level" in filters and course_number < filters["min_level"]:
                    is_eligible = False
                if 500 <= course_number < 600:
                    if constraints.get("allow_500_level", True) is False:
                        is_eligible = False
                if course_number >= 600:
                    allowed_600 = set(constraints.get("allowed_600_level_courses", []))
                    if course not in allowed_600:
                        is_eligible = False
                if is_eligible:
                    eligible_for_req.add(course)


    # -----------------------------
    # Create variables
    # -----------------------------

    take = {}

    for course in all_courses:
        for s in semesters:
            take[(course, s)] = model.new_bool_var(
                f"take_{course.replace(' ', '_')}_semester_{s}"
            )
    # -----------------------------
    # Cross-listed course constraints
    # -----------------------------

    cross_list_groups = set()

    for course in all_courses:
        row = course_to_row[course]

        cross_listed_courses = row.get("cross_list", [])

        if not isinstance(cross_listed_courses, list):
            continue

        group = {course}

        for cross_course in cross_listed_courses:
            if cross_course in all_courses:
                group.add(cross_course)

        if len(group) > 1:
            cross_list_groups.add(frozenset(group))




    for group in cross_list_groups:
        completed_count = sum(
            1 for course in group
            if course in completed_courses
        )

        future_count = sum(
            take[(course, s)]
            for course in group
            if course in all_courses and course not in completed_courses
            for s in semesters
        )

        model.add(completed_count + future_count <= 1)

    # -----------------------------
    # Each course at most once
    # -----------------------------

    for course in all_courses:
        model.add(
            sum(take[(course, s)] for s in semesters) <= 1
        )
    # Completed courses should not be scheduled

    for course in completed_courses:

        if course in all_courses:

            model.add(

                sum(take[(course, s)] for s in semesters) == 0

            )




    # -----------------------------
    # Degree requirement assignment variables
    # -----------------------------

    req_available_courses = {}
    use_for_req = {}

    for req in degree_requirements:
        req_id = req["id"]

        available_courses = []

        if "courses" in req:
            available_courses = [
                course for course in req["courses"]
                if course in all_courses or course in completed_courses
            ]

        elif "filters" in req:
            filters = req.get("filters", {})
            constraints = req.get("constraints", {})

            for course in all_courses:
                row = course_to_row[course]
                subject = str(row["subject"]).strip()

                try:
                    course_number = int(row["course_number"])
                except:
                    continue

                if "subject" in filters and subject != filters["subject"]:
                    continue

                if "min_level" in filters and course_number < filters["min_level"]:
                    continue

                if 500 <= course_number < 600:
                    if constraints.get("allow_500_level", True) is False:
                        continue

                if course_number >= 600:
                    allowed_600 = set(
                        constraints.get("allowed_600_level_courses", [])
                    )

                    if course not in allowed_600:
                        continue

                available_courses.append(course)

        req_available_courses[req_id] = available_courses

        for course in available_courses:
            use_for_req[(course, req_id)] = model.new_bool_var(
                f"use_{course.replace(' ', '_')}_for_{req_id}"
            )

            if course in completed_courses:
                # Completed course can be assigned to a requirement.
                pass
            else:
                # Future course can only satisfy requirement if it is taken.
                model.add(
                    use_for_req[(course, req_id)]
                    <= sum(take[(course, s)] for s in semesters)
                )

    # -----------------------------
    # Prevent double-counting across degree requirements
    # -----------------------------

    for course in set(course for course, _ in use_for_req):
        model.add(
            sum(
                use_for_req[(course, req_id)]
                for req_id in req_available_courses
                if (course, req_id) in use_for_req
            ) <= 1
        )

    # -----------------------------
    # Degree requirement constraints
    # -----------------------------

    for req in degree_requirements:
        req_id = req["id"]
        available_courses = req_available_courses[req_id]

        if req["requirement_type"] == "required_courses":
            for course in available_courses:
                model.add(
                    use_for_req[(course, req_id)] == 1
                )

        elif req["requirement_type"] == "choose_n":
            model.add(
                sum(
                    use_for_req[(course, req_id)]
                    for course in available_courses
                ) >= req["min_count"]
            )

            if "max_count" in req:
                model.add(
                    sum(
                        use_for_req[(course, req_id)]
                        for course in available_courses
                    ) <= req["max_count"]
                )

        constraints = req.get("constraints", {})

        for group in constraints.get("max_from_group", []):
            group_courses = [
                course for course in group["courses"]
                if course in available_courses
            ]

            model.add(
                sum(
                    use_for_req[(course, req_id)]
                    for course in group_courses
                ) <= group["max_count"]
            )



    # -----------------------------
    # Distribution requirements
    # -----------------------------

    satisfy_dist = {}

    for dist, min_courses in distribution_requirements.items():

        #Seaching for all valid distribution courses
        valid_courses = [
            course for course in distribution_courses[dist]
            if course in all_courses
        ]

        for course in valid_courses:
            if course not in completed_courses:

                # Course in distribution but has not been taken
                satisfy_dist[(course, dist)] = model.new_bool_var(
                    f"satisfy_{dist.replace(' ', '_')}_{course.replace(' ', '_')}"
                )

                # A course can satisfy distribution only if it is taken
                model.add(
                    satisfy_dist[(course, dist)]
                    <= sum(take[(course, s)] for s in semesters)
                )

        #Distribution courses that are completed
        completed_satisfying_courses = [
            course for course in valid_courses
            if course in completed_courses
        ]


        #Distribution courses that are not completed

        future_satisfying_sum = sum(
            satisfy_dist[(course, dist)]
            for course in valid_courses
            if course not in completed_courses
        )

        model.add(
            len(completed_satisfying_courses) + future_satisfying_sum >= min_courses
        )


        subjects = set(course.split(" ")[0] for course in valid_courses)

        for subject in subjects:
            completed_from_subject = min(2, sum(
                1 for course in completed_satisfying_courses
                if course.split(" ")[0] == subject
            ))

            future_from_subject = sum(
                satisfy_dist[(course, dist)]
                for course in valid_courses
                if course not in completed_courses
                and course.split(" ")[0] == subject
            )

            model.add(
                completed_from_subject + future_from_subject <= 2
            )

    # -----------------------------
    # Analyzing diversity requirement
    # -----------------------------

    valid_diversity_courses = [

        course for course in diversity_courses

        if course in all_courses

    ]

    diversity_already_completed = any(

        course in completed_courses

        for course in valid_diversity_courses

    )

    if not diversity_already_completed:

        model.add(

            sum(

                take[(course, s)]

                for course in valid_diversity_courses

                if course not in completed_courses

                for s in semesters

            ) >= 1

        )

    # -----------------------------
    # FWIS requirement
    # -----------------------------

    valid_fwis_courses = [

        course for course in fwis_courses

        if course in all_courses

        and course not in completed_courses

    ]

    fwis_already_completed = any(

        course in completed_courses

        for course in fwis_courses

    )

    if not fwis_already_completed:

        model.add(

            sum(

                take[(course, s)]

                for course in valid_fwis_courses

                for s in semesters

                if s < len(semesters) - 6


            ) == 1

        )

    # -----------------------------
    # LPAP requirement
    # -----------------------------

    valid_lpap_courses = [

        course for course in lpap_courses

        if course in all_courses

        and course not in completed_courses

    ]

    lpap_already_completed = any(

        course in completed_courses

        for course in lpap_courses

    )

    if not lpap_already_completed:

        model.add(

            sum(

                take[(course, s)]

                for course in valid_lpap_courses

                for s in semesters

            ) == 1

        )


    # -----------------------------
    # Prerequisite requirements
    # -----------------------------

    for course in all_courses:
        prereq_tree = get_prereq_tree(course)

        if prereq_tree is None:
            continue

        for s in semesters:
            prereq_ok = prereq_satisfied_bool(
                prereq_tree,
                s,
                model,
                take,
                completed_courses

            )

            model.add(
                take[(course, s)] <= prereq_ok
            )

    # -----------------------------
    # Fall/Spring availability
    # -----------------------------

    for course in all_courses:
        rows = df[df.apply(normalize_course, axis=1) == course]

        if rows.empty:
            continue

        offered_fall = rows["term"].astype(str).str.contains(
            "Fall", case=False, na=False
        ).any()

        offered_spring = rows["term"].astype(str).str.contains(
            "Spring", case=False, na=False
        ).any()

        if not offered_fall and not offered_spring:
            continue

        if current_term == "Spring":

            for s in semesters:
                if s % 2 == 0 and not offered_spring:

                    model.add(take[(course, s)] == 0)

                if s % 2 == 1 and not offered_fall:

                    model.add(take[(course, s)] == 0)
        elif current_term == "Fall":


            for s in semesters:
                if s % 2 == 0 and not offered_fall:

                    model.add(take[(course, s)] == 0)

                if s % 2 == 1 and not offered_spring:

                    model.add(take[(course, s)] == 0)


    # -----------------------------
    # Total credits >= 120
    # -----------------------------

    total_credits = sum(
        course_to_credits[course] * take[(course, s)]
        for course in all_courses
        if course in course_to_credits
        for s in semesters
    )

    completed_credit_total = sum(

    course_to_credits.get(course, 0)

    for course in completed_courses

)

    model.add(total_credits + completed_credit_total >= 120)

    # -----------------------------
    # Semester credit limit <= 18
    # -----------------------------

    for s in semesters:
        semester_credits = sum(
            course_to_credits[course] * take[(course, s)]
            for course in all_courses
            if course in course_to_credits
        )

        model.add(semester_credits <= 18)

    # -----------------------------
    # User preferred courses
    # -----------------------------


    for course in preferred_courses:

        if course in all_courses and course not in completed_courses:

            model.add(

                sum(take[(course, s)] for s in semesters) == 1

            )
    # -----------------------------

    # Courses student wants to avoid

    # -----------------------------

    for course in avoid_courses:

        if course in all_courses and course not in completed_courses:

            model.add(

                sum(take[(course, s)] for s in semesters) == 0

            )


    # -----------------------------
    # Semester used variables
    # -----------------------------

    semester_used = {}

    for s in semesters:
        semester_used[s] = model.new_bool_var(f"semester_{s}_used")

    for course in all_courses:
        for s in semesters:
            model.add(take[(course, s)] <= semester_used[s])

    # Prevent skipped semesters
    for s in range(len(semesters) - 1):
        model.add(semester_used[s] >= semester_used[s + 1])

    # -----------------------------
    # Objective
    # -----------------------------


    # Objective 1: Graduate as early as possible


    if optimization == "graduate early":
        required_or_choice_courses = set()

        for req in degree_requirements:
            if "courses" in req:
                required_or_choice_courses.update(req["courses"])

        model.minimize(
            1000 * sum(semester_used[s] for s in semesters)
            + total_credits
            + 10 * sum(
                s * take[(course, s)]
                for course in required_or_choice_courses
                if course in all_courses
                for s in semesters
            )
        )

    # Objective 2: Take balanced and graduate within 4 years
    elif optimization == "balanced":
        required_or_choice_courses = set()

        for req in degree_requirements:
            if "courses" in req:
                required_or_choice_courses.update(req["courses"])

        MIN_COMFORT = 0
        MAX_COMFORT = 16
        MAX_CREDITS = 18

        semester_credit_expr = {}
        credit_penalty = {}

        for s in semesters:
            semester_credit_expr[s] = sum(
                course_to_credits[course] * take[(course, s)]
                for course in all_courses
                if course in course_to_credits
            )

            credit_penalty[s] = model.new_int_var(
                0,
                MAX_CREDITS,
                f"credit_penalty_{s}"
            )

            # penalty if below 14
            model.add(credit_penalty[s] >= MIN_COMFORT - semester_credit_expr[s])

            # penalty if above 16
            model.add(credit_penalty[s] >= semester_credit_expr[s] - MAX_COMFORT)

            # no negative penalty
            model.add(credit_penalty[s] >= 0)

        model.minimize(
            100 * sum(credit_penalty[s] for s in semesters)
            + 50 * total_credits
            + sum(
                s * take[(course, s)]
                for course in required_or_choice_courses
                if course in all_courses
                for s in semesters
            )
        )

    # Print to debug before solving
    print("\n----Debug Before Solving----")
    print("Number of courses considered for `take` variables:", len(all_courses))
    print("Number of take variables created:", len(take))
    print("Completed credits:", completed_credit_total)
    print("Preferred courses:", preferred_courses)
    print("Avoid courses:", avoid_courses)
    print("Optimization mode:", optimization)

    # -----------------------------
    # Solve
    # -----------------------------

    solver = cp_model.CpSolver()
    status = solver.solve(model)


    # Debug after solving
    print("\n----Solver Status----")
    print("Status code:", status)
    print("Status name:", solver.status_name(status))


    def get_course_reason(course, semester_index):
        reasons = []

        if course in preferred_courses:
            reasons.append("student wants to take this course")

        for req in degree_requirements:
            req_id = req.get("id", "degree requirement")

            if (course, req_id) in use_for_req:
                if solver.value(use_for_req[(course, req_id)]) == 1:
                    reasons.append(f"satisfies {req_id}")

            elif "filters" in req:
                filters = req.get("filters", {})

                row = course_to_row.get(course)

                if row is not None:
                    subject = str(row["subject"]).strip()

                    try:
                        course_number = int(row["course_number"])
                    except:
                        course_number = None

                    if course_number is not None:
                        subject_match = (
                            "subject" not in filters
                            or subject == filters["subject"]
                        )

                        level_match = (
                            "min_level" not in filters
                            or course_number >= filters["min_level"]
                        )

                        if subject_match and level_match:
                            reasons.append(f"satisfies {req_id}")

        for dist, courses in distribution_courses.items():
            if course in courses:
                reasons.append(f"can satisfy {dist}")

        if course in diversity_courses:
            reasons.append("can satisfy Analyzing Diversity")

        if course in fwis_courses:
            reasons.append("satisfies FWIS requirement")

        prereq_tree = get_prereq_tree(course)

        if prereq_tree is not None:
            reasons.append("prerequisites are satisfied by this semester")

        if current_term == "Spring":
            term_name = "Spring" if semester_index % 2 == 0 else "Fall"
        else:
            term_name = "Fall" if semester_index % 2 == 0 else "Spring"

        reasons.append(f"offered in {term_name}")

        if not reasons:
            reasons.append("chosen to help reach credit total")

        return "; ".join(reasons)

    if status in [cp_model.OPTIMAL, cp_model.FEASIBLE]:
        print("Solution found.\n")

        total_planned_credits = 0

        for s in semesters:
            courses_this_sem = []

            for course in sorted(all_courses):
                if solver.value(take[(course, s)]) == 1:
                    courses_this_sem.append(course)

            if courses_this_sem:
                semester_credit_count = sum(
                    course_to_credits.get(course, 0)
                    for course in courses_this_sem
                )

                total_planned_credits += semester_credit_count

                print(f"Semester {s + 1} ({semester_credit_count} credits)")

                for course in courses_this_sem:
                    reason = get_course_reason(course, s)
                    print(f"  - {course}")
                    print(f"    Reason: {reason}")

                print()

        print("Scheduled credits:", total_planned_credits)
        print("Completed Courses:", completed_credit_total)
        print("Total credits including completed:", total_planned_credits + completed_credit_total)
        print("Objective value:", int(solver.objective_value))
        # -----------------------------
        # Build planned courses set
        # -----------------------------

        planned_courses = set()

        for course in all_courses:
            for s in semesters:
                if solver.value(take[(course, s)]) == 1:
                    planned_courses.add(course)

        completed_set = set(completed_courses)
        completed_and_planned = completed_set | planned_courses

        # -----------------------------
        # Show requirement progress
        # -----------------------------

        print("\nRequirement Progress")
        print("--------------------")

        unsatisfied_requirements = []

        for req in degree_requirements:
            req_id = req.get("id", "Unnamed Requirement")

            if "courses" in req:
                available_courses = [
                    course for course in req["courses"]
                    if course in all_courses or course in completed_set
                ]

            elif "filters" in req:
                filters = req.get("filters", {})
                constraints = req.get("constraints", {})

                available_courses = []

                for course, row in course_to_row.items():
                    subject = str(row["subject"]).strip()

                    try:
                        course_number = int(row["course_number"])
                    except:
                        continue

                    if "subject" in filters and subject != filters["subject"]:
                        continue

                    if "min_level" in filters and course_number < filters["min_level"]:
                        continue

                    if 500 <= course_number < 600:
                        if constraints.get("allow_500_level", True) is False:
                            continue

                    if course_number >= 600:
                        allowed_600 = set(
                            constraints.get("allowed_600_level_courses", [])
                        )

                        if course not in allowed_600:
                            continue

                    available_courses.append(course)

            else:
                continue

            satisfied_courses = [
                course for course in available_courses
                if course in completed_and_planned
            ]

            if req["requirement_type"] == "required_courses":
                missing_courses = [
                    course for course in available_courses
                    if course not in completed_and_planned
                ]

                if missing_courses:
                    unsatisfied_requirements.append(
                        f"{req_id}: missing {missing_courses}"
                    )
                    print(f"{req_id}: Not satisfied")
                    print("  Missing:", missing_courses)
                else:
                    print(f"{req_id}: Satisfied")

            elif req["requirement_type"] == "choose_n":
                min_count = req["min_count"]
                satisfied_count = len(satisfied_courses)

                if satisfied_count < min_count:
                    unsatisfied_requirements.append(
                        f"{req_id}: {satisfied_count}/{min_count} courses completed"
                    )
                    print(f"{req_id}: Not satisfied")
                    print(f"  Progress: {satisfied_count}/{min_count}")
                else:
                    print(f"{req_id}: Satisfied")
                    print(f"  Progress: {satisfied_count}/{min_count}")
        # -----------------------------
        # Distribution progress
        # -----------------------------

        for dist, min_courses in distribution_requirements.items():
            valid_courses = [
                course for course in distribution_courses[dist]
                if course in completed_and_planned
            ]

            if len(valid_courses) < min_courses:
                unsatisfied_requirements.append(
                    f"{dist}: {len(valid_courses)}/{min_courses} courses completed"
                )
                print(f"{dist}: Not satisfied")
                print(f"  Progress: {len(valid_courses)}/{min_courses}")
            else:
                print(f"{dist}: Satisfied")
                print(f"  Progress: {len(valid_courses)}/{min_courses}")

        # -----------------------------
        # Diversity progress
        # -----------------------------

        diversity_satisfied = any(
            course in completed_and_planned
            for course in diversity_courses
        )

        if diversity_satisfied:
            print("Analyzing Diversity: Satisfied")
        else:
            print("Analyzing Diversity: Not satisfied")
            unsatisfied_requirements.append("Analyzing Diversity")

        # -----------------------------
        # FWIS progress
        # -----------------------------

        fwis_satisfied = any(
            course in completed_and_planned
            for course in fwis_courses
        )

        if fwis_satisfied:
            print("FWIS: Satisfied")
        else:
            print("FWIS: Not satisfied")
            unsatisfied_requirements.append("FWIS")

        # -----------------------------
        # Credit progress
        # -----------------------------

        total_completed_and_planned_credits = (
            completed_credit_total + total_planned_credits
        )

        if total_completed_and_planned_credits >= 120:
            print(f"Total Credits: Satisfied ({total_completed_and_planned_credits}/120)")
        else:
            print(f"Total Credits: Not satisfied ({total_completed_and_planned_credits}/120)")
            unsatisfied_requirements.append(
                f"Total Credits: {total_completed_and_planned_credits}/120"
            )

        # -----------------------------
        # Final unsatisfied summary
        # -----------------------------

        print("\nUnsatisfied Requirements")
        print("------------------------")

        if not unsatisfied_requirements:
            print("All requirements are satisfied.")
        else:
            for requirement in unsatisfied_requirements:
                print(f"- {requirement}")

    else:
        print("No solution found.")

"""# Apply Testing

## General Test
"""

# -----------------------------
# Upcoming Term
# -----------------------------

current_term = "Spring"

year = "Freshman"

# -----------------------------

# Remaining Semesters

# -----------------------------

year_order = [

    "Freshman",

    "Sophomore",

    "Junior",

    "Senior"

]

term_order = [

    "Fall",

    "Spring"

]

# -----------------------------
# Course that have been taken
# -----------------------------


completed_courses = {

    "MATH 101",

    "MATH 102",

    "ECON 113",

    "ECON 111",

    "PHYS 101",

    "PHYS 102",

    "COMP 105",

    # freshman fall completed

    "COMP 140",

    "MATH 212",

    "MATH 355",

    "ECON 100"

}

# -----------------------------
# Courses student wants to take
# -----------------------------


preferred_courses = {

    "COMP 341",

    "COMP 449",

    "COMP 484"


}

# -----------------------------
# Courses student wants to avoid
# -----------------------------


avoid_courses = {

    "COMP 414"



}

# -----------------------------
# Different optimization
# -----------------------------

optimization = "balanced" # (graduate early, balanced)

main(
    df=df,
    degree_requirements=degree_requirements,
    completed_courses=completed_courses,
    preferred_courses=preferred_courses,
    avoid_courses=avoid_courses,
    current_term=current_term,
    year=year,
    optimization=optimization
)

"""#"""

# -----------------------------
# Upcoming Term
# -----------------------------

current_term = "Fall"

year = "Freshman"

# -----------------------------

# Remaining Semesters

# -----------------------------

year_order = [

    "Freshman",

    "Sophomore",

    "Junior",

    "Senior"

]

term_order = [

    "Fall",

    "Spring"

]

# -----------------------------
# Course that have been taken
# -----------------------------


completed_courses = {

    "MATH 101": 3,

    "MATH 102": 3,

    "ECON 113": 3,

    "ECON 111": 3,

    "PHYS 101": 3,

    "PHYS 102": 3,

    "COMP 105": 3,



}

# -----------------------------
# Courses student wants to take
# -----------------------------


preferred_courses = {



}

# -----------------------------
# Courses student wants to avoid
# -----------------------------


avoid_courses = {
    "COMP 646"





}

# -----------------------------
# Different optimization
# -----------------------------

optimization = "graduate early" # (graduate early, balanced)

main(
    df=df,
    degree_requirements=degree_requirements,
    completed_courses=completed_courses,
    preferred_courses=preferred_courses,
    avoid_courses=avoid_courses,
    current_term=current_term,
    year=year,
    optimization=optimization
)

# -----------------------------
# Upcoming Term
# -----------------------------

current_term = "Spring"

year = "Senior"

# -----------------------------

# Remaining Semesters

# -----------------------------

year_order = [

    "Freshman",

    "Sophomore",

    "Junior",

    "Senior"

]

term_order = [

    "Fall",

    "Spring"

]

# -----------------------------
# Course that have been taken
# -----------------------------


completed_courses = {

    "MATH 101",

    "MATH 102",

    "ECON 113",

    "ECON 111",

    "PHYS 101",

    "PHYS 102",

    "COMP 105",

    #Freshman Fall

    "COMP 140",

    "MATH 212",

    "MATH 355",

    "ECON 100",

    #Freshman Spring

    "FWIS 235",

    "ASIA 360",

    "COMP 182",

    "DSCI 301",

    "ECON 210",


    #Sophomore Fall

    "COMP 215",

    "COMP 222",

    "COMP 341",

    "COMP 414"



}

# -----------------------------
# Courses student wants to take
# -----------------------------


preferred_courses = {

  "COMP 468",

  "COMP 440",

  "COMP 421",

  "COMP 282",

  "PHIL 101",



}

# -----------------------------
# Courses student wants to avoid
# -----------------------------


avoid_courses = {





}

# -----------------------------
# Different optimization
# -----------------------------

optimization = "graduate early" # (graduate early, balanced)

main(
    df=df,
    degree_requirements=degree_requirements,
    completed_courses=completed_courses,
    preferred_courses=preferred_courses,
    avoid_courses=avoid_courses,
    current_term=current_term,
    year=year,
    optimization=optimization
)