"""create courses table

Revision ID: ca2affb78d11
Revises: 
Create Date: 2026-05-28 11:17:07.786234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2affb78d11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('overall_workload', sa.Integer(), nullable=True),
    sa.Column('content_difficulty', sa.Integer(), nullable=True),
    sa.Column('exam_difficulty', sa.Integer(), nullable=True),
    sa.Column('project_assignment_difficulty', sa.Integer(), nullable=True),
    sa.Column('instructor', sa.Integer(), nullable=True),
    sa.Column('practical_usefulness', sa.Integer(), nullable=True),
    sa.Column('interest_enjoyment', sa.Integer(), nullable=True),
    sa.Column('user_like', sa.Text(), nullable=True),
    sa.Column('user_dislike', sa.Text(), nullable=True),
    sa.Column('course_number', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
